const ace='https://www.acefitness.org/resources/everyone/exercise-library/'
const machine='https://kb.cybexintl.com/Product_Info/Life_Fitness_Circuit_Series_Machine_Use_Instructions.pdf'
const guide=(kind,variant,setup,execution,cues,source)=>({kind,variant,setup,execution,cues,source})

export const exerciseGuides={
  'Bankdrücken':guide('bench','Flachbank mit Langhantel',
    ['Füße fest aufstellen; Kopf, oberer Rücken und Gesäß bleiben auf der Bank.','Stange mit geschlossenem Griff halten; Unterarme in der unteren Position ungefähr senkrecht.'],
    ['Stange kontrolliert zur Brust absenken, ohne sie aufprallen zu lassen.','Nach oben drücken und anschließend wieder kontrolliert absenken.'],
    ['Handgelenke über den Unterarmen halten.','Gesäß auf der Bank lassen; Ablage bzw. Sicherung passend einstellen.'],
    'https://www.acefitness.org/certifiednewsarticle/2884/ace-sponsored-research-top-3-most-effective-chest-exercises/'),
  'Beinbeugen im Sitzen':guide('legcurl','Sitzende Beinbeugermaschine',
    ['Knie an der Drehachse ausrichten; Oberschenkelpolster fixieren.','Rücken anlehnen, Unterschenkel auf die Rolle legen.'],
    ['Fersen nach unten und unter den Sitz ziehen.','Beine kontrolliert wieder strecken.'],
    ['Becken bleibt auf dem Sitz.','Gerätegriffe dienen der Stabilisierung.'],machine),
  'Beinpresse':guide('legpress','Sitzende bzw. schräge Beinpresse',
    ['Rücken und Becken anlehnen; Füße vollständig auf die Plattform stellen.','Fußabstand so wählen, dass die Knie den Fußspitzen folgen.'],
    ['Plattform durch Strecken der Beine wegdrücken.','Kontrolliert absenken, solange Becken und Rücken anliegen.'],
    ['Knie nicht ruckartig durchdrücken.','Fersen bleiben auf der Plattform.'],ace+'154/seated-leg-press/'),
  'Bizepsmaschine':guide('biceps','Bizepsmaschine mit Oberarmauflage',
    ['Sitz so einstellen, dass Ellbogen zur Gerätedrehachse passen.','Oberarme auflegen und Griffe halten.'],
    ['Ellbogen beugen und Griffe heranziehen.','Kontrolliert zurückführen.'],
    ['Oberarme auf der Auflage lassen.','Handgelenke nicht abknicken.'],machine),
  'Face Pulls im Sitzen am Kabelzug':guide('facepull','Sitzender Face Pull am Seil',
    ['Seil ungefähr auf Augenhöhe befestigen; aufrecht und stabil sitzen.','Arme nach vorn ausstrecken und leichte Seilspannung herstellen.'],
    ['Seil zum Gesicht ziehen und die Enden seitlich am Kopf vorbeiführen.','Ellbogen nach außen und hinten führen; kontrolliert zurückstrecken.'],
    ['Oberkörper bleibt ruhig.','Nicht mit dem Kopf dem Seil entgegengehen.'],
    'https://www.nasm.org/resource-center/exercise-library/face-pull'),
  'Hammercurls':guide('hammer','Stehend mit Kurzhanteln',
    ['Hanteln neben dem Körper halten, Handflächen zeigen zueinander.','Füße stabil aufstellen; Ellbogen nah am Rumpf.'],
    ['Ellbogen beugen und Hanteln anheben, ohne den Griff zu drehen.','Langsam wieder absenken.'],
    ['Keinen Schwung aus dem Oberkörper holen.','Handgelenke bleiben gerade.'],ace+'10/hammer-curl/'),
  'Jefferson Curls':guide('jefferson','Kontrolliertes Ab- und Aufrollen',
    ['Stabil stehen, Knie locker und Gewicht vor dem Körper halten.','Nur den bereits eingeübten Bewegungsumfang nutzen.'],
    ['Kopf und Oberkörper kontrolliert nach vorn abrollen; Arme hängen lassen.','Aus der unteren Position kontrolliert wieder aufrollen.'],
    ['Nicht federn oder Tiefe erzwingen.','Den Bewegungsumfang kontrolliert und ohne erzwungene Endtiefe wählen.'],
    'https://e3rehab.com/ranking-the-5-most-dangerous-exercises/'),
  'Latzug':guide('lat','Latzug vor dem Körper',
    ['Oberschenkel unter dem Polster fixieren und Griff sicher fassen.','Rumpf stabil halten und höchstens leicht zurücklehnen.'],
    ['Ellbogen nach unten führen; Griff zur oberen Brust ziehen.','Griff kontrolliert nach oben zurückführen.'],
    ['Nicht in den Nacken ziehen.','Keinen Schwung aus dem Rücken holen.'],ace+'158/seated-lat-pulldown/'),
  'Rudern mit Brustauflage eng':guide('row','Enges Rudern mit Brustpolster',
    ['Sitz und Brustauflage passend einstellen; Füße abstützen.','Brust anlegen und enge Griffe fassen.'],
    ['Griffe zum Rumpf ziehen; Ellbogen körpernah nach hinten führen.','Arme kontrolliert wieder nach vorn führen.'],
    ['Brustkontakt halten.','Schultern nicht zu den Ohren ziehen.'],machine),
  'Schulterpresse':guide('shoulder','Sitzende Schulterpresse',
    ['Rücken anlehnen; Griffe etwa auf Schulterhöhe einstellen.','Füße fest aufstellen und Handgelenke über den Unterarmen halten.'],
    ['Griffe über den Kopf drücken, ohne ins Hohlkreuz auszuweichen.','Kontrolliert bis zur Ausgangsposition zurückführen.'],
    ['Ellbogen nicht ruckartig verriegeln.','Kopf und Rumpf ruhig halten.'],ace+'186/seated-shoulder-press/'),
  'Seitheben':guide('lateral','Stehend mit Kurzhanteln',
    ['Hanteln seitlich halten; Ellbogen leicht beugen.','Rumpf stabil und Handgelenke gerade halten.'],
    ['Arme seitlich ungefähr bis Schulterhöhe anheben.','Kontrolliert absenken.'],
    ['Ellbogen und Oberarme führen die Bewegung.','Nicht hochschwingen oder die Schultern hochziehen.'],ace+'26/lateral-raise/'),
  'Trizepsdrücken':guide('pushdown','Trizepsdrücken am hohen Kabelzug',
    ['Hohen Kabelzug mit Seil oder Stange nutzen; stabil davor stehen.','Oberarme neben dem Rumpf halten, Ellbogen beugen.'],
    ['Ellbogen strecken und Griff nach unten führen.','Unterarme kontrolliert zurückführen.'],
    ['Oberarme bleiben möglichst ruhig.','Nicht mit dem Körpergewicht nach unten drücken.'],ace+'3/triceps-pressdown/'),
  'Trizepsdrücken über dem Kopf':guide('overhead','Überkopf-Trizepsstrecken mit Kurzhantel',
    ['Gewicht sicher über dem Kopf halten; Oberarme zeigen nach oben.','Rumpf stabilisieren und Ellbogen ungefähr schulterbreit halten.'],
    ['Gewicht durch Beugen der Ellbogen hinter den Kopf absenken.','Ellbogen kontrolliert wieder strecken.'],
    ['Oberarme und Rumpf möglichst ruhig halten.','Bei der Kabelvariante bleibt die Ellbogenbewegung gleich; die Zugrichtung hängt vom Kabelaufbau ab.'],ace+'74/triceps-extension/'),
}

export function guideForExercise(name) {
  const normalized=String(name??'').trim().toLocaleLowerCase('de-DE')
  return Object.entries(exerciseGuides).find(([key])=>key.toLocaleLowerCase('de-DE')===normalized)?.[1]??null
}
